name: Créer PyTN

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
        
      - name: Run Python Script
        run: 'python ./python_last_version.py'         

        
      - name: Download Dependencies
        run: py -m pip download -r "./requirements.txt" -d depsx64
        
      - name: Ajout des autres whl
        run: cp *.whl depsx64
        
      - name: read 
        run: |
          VERSION=$(cat python.version)
          MAJOR=$(echo $VERSION | cut -d'.' -f1)
          MINOR=$(echo $VERSION | cut -d'.' -f2)
          PATCH=$(echo $VERSION | cut -d'.' -f3)
          echo "::set-output name=major::$MAJOR"
          echo "::set-output name=minor::$MINOR"
          echo "::set-output name=patch::$PATCH"
      
      - uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with: 
          filepath: './simpleInstallerWin10x64.iss /dmajor=${MAJOR} /dminor=${MINOR} /dpatch=${PATCH}'
        
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mysetup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
