name: Créer PyTN

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
        
      - name: Run Python Script
        run: 'python ./python_last_version.py'         

        
      - name: Download Dependencies
        run: py -m pip download -r "./requirements.txt" -d depsx64
        
      - name: Ajout des autres whl
        run: cp *.whl depsx64
        
      - name: read python version components
        shell: cmd
        run: |
          for /f "delims=" %%i in (python.version) do set VERSION=%%i
          for /f "tokens=1,2,3 delims=." %%a in ("%VERSION%") do (
              set MAJOR=%%a
              set MINOR=%%b
              set PATCH=%%c
          )
      - name: Save major version
        run: |
          echo "MAJOR=${{ env.MAJOR_VERSION }}" >> $GITHUB_STATE
          echo "Major version: $MAJOR_VERSION"
      
      - name: Save minor version
        run: |
          echo "MINOR=${{ env.MINOR_VERSION }}" >> $GITHUB_STATE
          echo "Minor version: $MINOR_VERSION"
      
      - name: Save patch version
        run: |
          echo "PATCH=${{ env.PATCH_VERSION }}" >> $GITHUB_STATE
          echo "Patch version: $PATCH_VERSION"
      
      - uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with: 
          filepath: './simpleInstallerWin10x64.iss /dmajor=${MAJOR} /dminor=${MINOR} /dpatch=${PATCH}'
        
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mysetup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
